# Generated by Django 2.1.5 on 2019-12-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MinecraftDB', '0003_food_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mineral_name', models.CharField(max_length=20)),
                ('Generate_Range', models.FloatField(default=0)),
            ],
        ),
    ]
