# Generated by Django 2.1.5 on 2019-12-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MinecraftDB', '0005_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weather_name', models.CharField(max_length=20)),
                ('Weather_Explain', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('World_name', models.CharField(max_length=20)),
                ('Arrival_Way', models.CharField(max_length=20)),
                ('World_Explain', models.CharField(max_length=20)),
                ('Terrain_Generate', models.CharField(max_length=20)),
                ('Weather_Generate', models.CharField(max_length=20)),
            ],
        ),
    ]
