# Generated by Django 2.1.5 on 2019-12-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MinecraftDB', '0007_building_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_name', models.CharField(max_length=20)),
                ('Account_number', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Profile', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member_Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_Diary_name', models.CharField(max_length=20)),
                ('Diary', models.TextField()),
                ('picture', models.ImageField(default='', upload_to='pictures')),
            ],
        ),
    ]
