# Generated by Django 2.1.5 on 2019-12-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MinecraftDB', '0008_member_member_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_diary',
            name='Tilte',
            field=models.CharField(default='myDiary', max_length=20),
        ),
    ]
