# Generated by Django 2.1.5 on 2019-12-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MinecraftDB', '0009_member_diary_tilte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_diary',
            old_name='Tilte',
            new_name='Title',
        ),
    ]
