# Generated by Django 2.1.5 on 2019-12-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MinecraftDB', '0010_auto_20191218_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_diary',
            name='picture',
            field=models.ImageField(default='', null=True, upload_to='pictures'),
        ),
    ]
